In [5]:
import tarfile
import pyprind
import numpy as np
import os
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

SyntaxError: source code string cannot contain null bytes (<string>)

In [8]:
#with tarfile.open("C:/Users/jesus/IA/machinelearning/machinelearningbook/archivos/curso4/aclImdb_v1.tar.gz", 'r:gz') as tar:
 #   tar.extractall(path="C:/Users/jesus/IA/machinelearning/machinelearningbook/archivos/curso4/movies")

C:\Users\jesus\AppData\Local\Temp\ipykernel_8160\2539065399.py:2: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path="C:/Users/jesus/IA/machinelearning/machinelearningbook/archivos/curso4/movies")

In [11]:
#basepath = 'C:/Users/jesus/IA/machinelearning/machinelearningbook/archivos/curso4/movies/aclImdb'

#labels = {'pos': 1, 'neg': 0}
#pbar = pyprind.ProgBar(50000)

#data = []  # lista para acumular

#for s in ('test', 'train'):
#    for l in ('pos', 'neg'):
#        path = os.path.join(basepath, s, l)
 #       for file in os.listdir(path):
 #           with open(os.path.join(path, file), 'r', encoding='utf-8') as infile:
  #              txt = infile.read()
 #           data.append([txt, labels[l]])  # acumula en la lista
 #           pbar.update()

# convertir lista a DataFrame
#df = pd.DataFrame(data, columns=['review', 'sentiment'])

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:08

In [12]:
#df.head()

                                              review  sentiment
0  I went and saw this movie last night after bei...          1
1  Actor turned director Bill Paxton follows up h...          1
2  As a recreational golfer with some knowledge o...          1
3  I saw this film in a sneak preview, and it is ...          1
4  Bill Paxton has taken the true story of the 19...          1

In [2]:
#np.random.seed(0)
#df = df.reindex(np.random.permutation(df.index))
#df.to_csv("C:/Users/jesus/IA/machinelearning/machinelearningbook/archivos/curso4/movies/movies_data.csv", index=False, encoding='utf-8')

NameError: name 'df' is not defined

In [2]:
df = pd.read_csv("C:/Users/jesus/IA/machinelearning/machinelearningbook/archivos/curso4/movies/movies_data.csv", encoding='utf-8')
df.rename(columns={'0': 'review', '1': 'sentiment'})
df.head()

                                              review  sentiment
0  In 1974, the teenager Martha Moxley (Maggie Gr...          1
1  OK... so... I really like Kris Kristofferson a...          0
2  ***SPOILER*** Do not read this, if you think a...          0
3  hi for all the people who have seen this wonde...          1
4  I recently bought the DVD, forgetting just how...          0

In [3]:
df.shape

(50000, 2)

In [4]:
count = CountVectorizer()
docs = np.array( [ 'The sun is shining', 'The weather is sweet', 'The sun is shining, the weather is sweet, and one and one is two'] )
bag = count.fit_transform(docs)

In [5]:
print(bag)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 17 stored elements and shape (3, 9)>
  Coords	Values
  (0, 6)	1
  (0, 4)	1
  (0, 1)	1
  (0, 3)	1
  (1, 6)	1
  (1, 1)	1
  (1, 8)	1
  (1, 5)	1
  (2, 6)	2
  (2, 4)	1
  (2, 1)	3
  (2, 3)	1
  (2, 8)	1
  (2, 5)	1
  (2, 0)	2
  (2, 2)	2
  (2, 7)	1

In [6]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}

In [7]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]

In [8]:
tfidf = TfidfTransformer(use_idf=False, norm='l2', smooth_idf=False)
np.set_printoptions(precision=2)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.   0.5  0.   0.5  0.5  0.   0.5  0.   0.  ]
 [0.   0.5  0.   0.   0.   0.5  0.5  0.   0.5 ]
 [0.39 0.59 0.39 0.2  0.2  0.2  0.39 0.2  0.2 ]]

In [9]:
def  preprocessor(text):
    text = re.sub(r'<[^>]*>', '', text)
    emoticons = re.findall(r'(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = ( re.sub(r'[\W]+', ' ', text.lower())) + ' '.join(emoticons).replace('-', '')
    return text

In [10]:
df['review'] = df['review'].apply(preprocessor)

In [11]:
def tokenizer(text):
    return text.split()

In [12]:
porter = PorterStemmer()
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

In [13]:
tokenizer('runners like running and thus they run')

['runners', 'like', 'running', 'and', 'thus', 'they', 'run']

In [14]:
tokenizer_porter('runners like running and thus they run')

['runner', 'like', 'run', 'and', 'thu', 'they', 'run']

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jesus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [16]:
stop = stopwords.words('english')

In [17]:
[w for w in tokenizer_porter('a runner likes running and runs a lot')[-10:]
if w not in stop]

['runner', 'like', 'run', 'run', 'lot']

In [18]:
X_train = df.loc[:25000, 'review'].values
y_train = df.loc[:25000, 'sentiment'].values
X_test = df.loc[25000:, 'review'].values
y_test = df.loc[25000:, 'sentiment'].values

In [36]:
tfidf = TfidfVectorizer(strip_accents=None, lowercase=False, preprocessor=None)
param_grid = [{'vect__ngram_range': [(1, 1)],
               'vect__stop_words': [stop, None],
               'vect__tokenizer': [tokenizer, tokenizer_porter],
               'clf__penalty': ['l1', 'l2'],
               'clf__C': [1.0, 10.0, 100.0]},
              {'vect__ngram_range': [(1, 1)],
               'vect__stop_words': [stop, None],
               'vect__tokenizer': [tokenizer, tokenizer_porter],
               'vect__use_idf':[False],
               'vect__norm':[None],
               'clf__penalty': ['l1', 'l2'],
               'clf__C': [1.0, 10.0, 100.0]},
              ]

In [37]:
lr_tfidf = Pipeline([ ('vect', tfidf), ('clf', LogisticRegression(solver='liblinear')) ])

In [38]:
gs_lr_tfidf = GridSearchCV(lr_tfidf, param_grid, scoring='accuracy', cv=5, n_jobs=-1, verbose=2)

In [ ]:
gs_lr_tfidf.fit(X_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

In [ ]:
print('Best parameter set: %s ' % gs_lr_tfidf.best_params_)
print('CV Accuracy: %.3f' % gs_lr_tfidf.best_score_)

In [ ]:
clf = gs_lr_tfidf.best_estimator_
print('Test Accuracy: %.3f' % clf.score(X_test, y_test))

In [19]:
def  tokenizer(text):
    text = re.sub(r'<[^>]*>', '', text)
    emoticons = re.findall(r'(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = ( re.sub(r'[\W]+', ' ', text.lower())) + ' '.join(emoticons).replace('-', '')
    tokenized = [w for w in text.split() if not w in stop]
    return tokenized

In [20]:
path = "C:/Users/jesus/IA/machinelearning/machinelearningbook/archivos/curso4/movies/movies_data.csv"

In [21]:
def stream_docs(path):
    with open(path, 'r', encoding='utf-8') as csv:
        next(csv)
        for line in csv:
            text, label = line[:-3], int(line[-2])
            yield text, label

In [22]:
next(stream_docs(path))

('"In 1974, the teenager Martha Moxley (Maggie Grace) moves to the high-class area of Belle Haven, Greenwich, Connecticut. On the Mischief Night, eve of Halloween, she was murdered in the backyard of her house and her murder remained unsolved. Twenty-two years later, the writer Mark Fuhrman (Christopher Meloni), who is a former LA detective that has fallen in disgrace for perjury in O.J. Simpson trial and moved to Idaho, decides to investigate the case with his partner Stephen Weeks (Andrew Mitchell) with the purpose of writing a book. The locals squirm and do not welcome them, but with the support of the retired detective Steve Carroll (Robert Forster) that was in charge of the investigation in the 70\'s, they discover the criminal and a net of power and money to cover the murder.<br /><br />""Murder in Greenwich"" is a good TV movie, with the true story of a murder of a fifteen years old girl that was committed by a wealthy teenager whose mother was a Kennedy. The powerful and rich family used their influence to cover the murder for more than twenty years. However, a snoopy detective and convicted perjurer in disgrace was able to disclose how the hideous crime was committed. The screenplay shows the investigation of Mark and the last days of Martha in parallel, but there is a lack of the emotion in the dramatization. My vote is seven.<br /><br />Title (Brazil): Not Available"',
 1)

In [28]:
def get_minibath(doc_stream, size):
    docs, y = [], []
    try:
        for _ in range(size):
            text, label = next(doc_stream)
            docs.append(text)
            y.append(label)
    except StopIteration:
        return None, None
    return docs, y

In [31]:
vect = HashingVectorizer( decode_error='ignore', n_features=2**21, preprocessor=None, tokenizer=tokenizer )
clf = SGDClassifier(loss='log_loss', random_state=1)
doc_stream = stream_docs(path)

In [32]:
pbar = pyprind.ProgBar(45)
classes = np.array([0,1])
for _ in range(45):
    X_train, y_train = get_minibath(doc_stream, 1000)
    if not X_train:
        break
    X_train = vect.transform(X_train)
    clf.partial_fit(X_train, y_train, classes=classes)
    pbar.update()

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:16

In [39]:
doc_stream = stream_docs(path)
print(doc_stream)
X_test, y_test = get_minibath(doc_stream, 5000)
X_test = vect.transform(X_test)
print('Accuracy: %.3f' % clf.score(X_test, y_test))

<generator object stream_docs at 0x0000022AF1E90640>
Accuracy: 0.878

In [40]:
clf = clf.partial_fit(X_test, y_test)

In [41]:
df.head()

                                              review  sentiment
0  in 1974 the teenager martha moxley maggie grac...          1
1  ok so i really like kris kristofferson and his...          0
2   spoiler do not read this if you think about w...          0
3  hi for all the people who have seen this wonde...          1
4  i recently bought the dvd forgetting just how ...          0

In [43]:
count = CountVectorizer(stop_words='english', max_df=.1, max_features=10000)
X = count.fit_transform(df['review'].values)

In [44]:
lda = LatentDirichletAllocation( n_components=10, random_state=123, learning_method='batch' )
x_topics = lda.fit_transform(X)

In [45]:
lda.components_.shape

(10, 10000)

In [46]:
n_stop_words = 5
feature_names = count.get_feature_names_out()
for topic_idx, topic in enumerate(lda.components_):
    print(f"Topic {(topic_idx + 1)}" )
    print(" ".join([feature_names[i] for i in topic.argsort()[:-n_stop_words - 1:-1]]))

Topic 1
worst minutes guy awful horror
Topic 2
book performance role father read
Topic 3
action series episode police guy
Topic 4
human sense audience viewer mind
Topic 5
family children feel kids school
Topic 6
music original musical animation songs
Topic 7
horror house performance woman role
Topic 8
comedy series jokes star episode
Topic 9
comedy role john plays played
Topic 10
war game american history german

In [49]:
horror = x_topics[:,5 ].argsort()[::-1]
for iter_idx, movie_idx in enumerate(horror[:3]):
    print(f" Horror Movie # {(iter_idx + 1)}:" )
    print(df["review"][movie_idx][:300], "...")

 Horror Movie # 1:
after the across the board success of my name is barbra cbs television permitted barbra to create an even more elaborate follow up as her second special streisand wisely knew in order to follow in the ground breaking success of my name is barbra that her second special would indeed need to raise the ...
 Horror Movie # 2:
the hand of death aka countdown in kung fu 1976 is a vastly underrated early work by director john woo the film stars dorian tan tan tao liang and features jackie chan sammo hung and james tien in significant supporting roles many people believe or have been lead to believe by deceptive advertising  ...
 Horror Movie # 3:
the hand of death aka countdown in kung fu 1976 is a vastly underrated early work by director john woo the film stars dorian tan tan tao liang and features jackie chan sammo hung and james tien in significant supporting roles many people believe or have been lead to believe by deceptive advertising  ...